### ISSUE TITLE
Error while building 

### ISSUE THREAD

**Issue by hessaHamad** [Carpediem324/WHEELTEC_N100_IMU_ROS2#2]
Dear, 

thank you for providing this driver, i have been trying to build it for a week. The attached photo shows the errors i get: 

![photo1707650823](https://github.com/Carpediem324/WHEELTEC_N100_IMU_ROS2/assets/122529202/260775d9-e7fb-4d2b-8885-5a11abac5acf)

OS = Linux (ubuntu 18.04)
Jetson Nano Developer kit 
ROS2 Crystal (since it is the latest for ubuntu 18.04) 

thank you 
BR,

**Comment by Carpediem324** [comment]
This driver is working on ubuntu 20.04 and ROS2 foxy version
I recommend to use docker on jetson nano and build on ROS2 foxy
